# Generated by Django 5.1.1 on 2024-11-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_person_uses_technology_alter_technology_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uses',
            old_name='Project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='uses',
            old_name='Technology',
            new_name='technology',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='version',
        ),
    ]
