# Generated by Django 5.1.1 on 2024-11-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_project_uses_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='version',
            field=models.CharField(default=0.0, max_length=64),
            preserve_default=False,
        ),
    ]
