# Generated by Django 5.1.1 on 2024-11-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_technology_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
